### ISSUE TITLE
Matching current MenuItem

### ISSUE THREAD

**Issue by phiamo** [KnpLabs/KnpMenuBundle#122]
Hi folks,
nice work!

I just updated to dev-master and dont get menu items matched anymore ...

is there any further change i have to implement, except for removing setCurrentURI calls?

cheers phil

**Comment by vishalmelmatti** [comment]
Hi,

I am able to get current item using

        $menu = $this->provider->get($menuName);

        $treeIterator = new RecursiveIteratorIterator(new RecursiveItemIterator(new ArrayIterator(array($menu))), RecursiveIteratorIterator::SELF_FIRST);

        $iterator = new CurrentItemFilterIterator($treeIterator, $this->matcher);

        $iterator->rewind();

        if ($iterator->valid()) {
            $current = $iterator->current();
            $current->setCurrent(true);
        } else {
            // Set Current as an empty Item in order to avoid exceptions on knp_menu_get
            $current = new MenuItem('', new MenuFactory());
        }

        return $current;

Is there a way to get previous and next item of menu ? This is very commonly needed like on blogs to navigate to previous and next posts.
