### ISSUE TITLE
possible that multi routes match one child?

### ISSUE THREAD

**Issue by symfonyluxury** [KnpLabs/KnpMenuBundle#128]
I want several routes map to the same menu child, but if I click this child link, it would direct me to one of their specified route

**Comment by WouterJ** [comment]
This looks rather strange to me. It means you want one link to link to multiple pages? That's not something HTML supports by default and as such, it's not something knp menu can help with.

As this is a very old issue and not much people showed their interest in such a feature, I'm going to close this issue.

**Comment by stof** [comment]
Well, actually, this is possible. the RouteVoter allows to specify multiple routes which will match the item (even regexes).
the voters are not yet documented properly though. I suggest you to look at the code of the RouterVoter and its unit tests for now.

**Comment by iquito** [comment]
Important for using RouteVoter - you need to set "routes" via setExtra like this:

    $menu->addChild('Menu Item', ['route' => 'symfony_route'])->setExtra('routes', ['symfony_route', 'symfony_route2']);

This way all Symfony routes in the "routes" array are a match.
