### ISSUE TITLE
Translation - Menu label not translated

### ISSUE THREAD

**Issue by Maxwell2022** [KnpLabs/KnpMenuBundle#170]
Hi folks, 

I'm using `setExtra` to set the domain translation but the menu is not translating. I've cleared my cache and try to look where this is happening but could not find it. Do I need an extra bundle from kpnlabs or is it using the built-in translation of Symphony?

Version used:

``` shell
knplabs/knp-menu [v1.1.2] : An object oriented menu library
knplabs/knp-menu-bundle [v1.1.0] : This bundle provides an integration of the KnpMenu library
```

My menu buidler:

``` php
<?php
# src/Acme/DemoBundle/Menu/Builder.php

namespace Acme\DemoBundle\Menu;

use Knp\Menu\FactoryInterface;
use Symfony\Component\DependencyInjection\ContainerAware;

class Builder extends ContainerAware
{
    protected function getBaseMenu(FactoryInterface $factory, $options) {

        $root = $factory->createItem('root', $options);
        $root->setChildrenAttribute('id', 'menu');
        $root->setExtra('translation_domain', 'AcmeDemoBundle');
        $root->setCurrentUri($this->container->get('request')->getRequestUri());

        return $root;
    }

    public function mainMenu(FactoryInterface $factory, array $options)
    {
        $root = $this->getBaseMenu($factory, $options);

        $root->addChild('menu.home', array('route' => '_homepage'))->setExtra('translation_domain', 'AcmeDemoBundle');
        $root->addChild('menu.login', array('route' => 'fos_user_security_login'))->setExtra('translation_domain', 'AcmeDemoBundle');
        $root->addChild('menu.register', array('route' => 'fos_user_registration_register'))->setExtra('translation_domain', 'AcmeDemoBundle');

        return $root;
    }

    public function loggedInMenu(FactoryInterface $factory, array $options)
    {
        $root = $this->getBaseMenu($factory, $options);
        $root->addChild('menu.dashboard', array('route' => '_dashboard'))->setExtra('translation_domain', 'AcmeDemoBundle');;
        return $root;
    }
}
```

My template:

``` twig
{% if is_granted('ROLE_USER') %}
    {{ knp_menu_render('AcmeDemoBundle:Builder:loggedInMenu') }}
{% else %}
    {{ knp_menu_render('AcmeDemoBundle:Builder:mainMenu') }}
{% endif %}
```

The translation file:

``` yaml
# src/Acme/DemoBundle/Resources/translations/AcmeDemoBundle.en.yml
menu:
    home: Home
    login: Login
    register: Register
    dashboard: Home
```

But the labels in my menu are displayed like this: `menu.home`, `menu.login`, `menu.register` and `menu.dashboard`

I've followed the readme but without success. Actually I even tried to not set the domain and use `message.en.yml` but no chance :(

I've tried to put those translation files under the app folder (`app/Resources/translations`) but it's not working neither. I've also tried to add a `label` option adding the child but nothing. What am I missing?

I've tried to debug it but I can't see where translation is meant to be done. I've looked into the `Renderer` but could not find anything.

I don't know if it's a bug or if it's me.
Cheers, 

Maxime

**Comment by nicodmf** [comment]
https://github.com/KnpLabs/KnpMenuBundle/blob/master/Resources/doc/i18n.rst

**Comment by sourcerer-mike** [comment]
This again is an issue to me, as the docs don't provide enough information on this.

https://github.com/KnpLabs/KnpMenuBundle/blob/master/Resources/doc/i18n.rst

I got almost the same setup as Maxwell2022 above. Clearing the cache, the labels are not translated. I did not find any documentation how to change the template.

**Comment by peschee** [comment]
The translation of the menu items by default seems to be merged in #280. However, this is in the `master` branch so I assume you'll have to checkout the `dev-master` version @sourcerer-mike

**Comment by matudelatower** [comment]
@nicodmf doesnt work form me https://github.com/KnpLabs/KnpMenuBundle/blob/master/Resources/doc/i18n.rst

im use: 
```php
		$menu[ $keyEmpresa ]
			->addChild(
				$this->container->get( 'translator' )->trans( 'menu.empresa.publicaciones',
					array( ),
					'app' ),
				array(
					'route' => 'empresa_perfil',
				)
			);
```

**Comment by nicodmf** [comment]
@matudelatower the documentation has changed, for me this was work : https://github.com/KnpLabs/KnpMenuBundle/blob/8cf6329e63e4bb8a14336c6facaa8d5f48f80f52/Resources/doc/i18n.rst this was in twig, more beautiful in my mind, and in just one place.

**Comment by AmaliDeveloper** [comment]
you can get th solution in this tutorial https://youtu.be/fcwUUGxlTIM
