### ISSUE TITLE
safe_label and allow_safe_label still escaping HTML

### ISSUE THREAD

**Issue by dotstormz** [KnpLabs/KnpMenuBundle#222]
I am attempting to add an image to one individual menu item by using the extras => safe_label option. This does not allow for an image to be rendered as HTML and instead shows the text: <img src='/bundles/acme/images/btn-login-signup.png'>.

Builder.php

``` php
public function accountMenu(FactoryInterface $factory, array $options)
    {
        $menu = $factory->createItem('main_right');
        $image = "<img src='/bundles/acmetest/images/btn-login-signup.png'>";
        $menu->addChild(
            $image,
            array(
                'route' => 'some_route',
                'extras' => array(
                    'safe_label' => true
                )
            )
        );

        return $menu;
    }
```

TWIG template:

``` Twig
{{ knp_menu_render('AcmeTestBundle:Builder:accountMenu', { 'currentClass': 'active', 'ancestorClass': 'active', 'allow_‌​safe_labels': true })|raw }}
```

This is using the following:
- Updating knplabs/knp-menu dev-master (8206c3a => ff1a6e7) Checking out ff1a6e73e79c9f75c6a130d03b07f05c89fede63
- Updating knplabs/knp-menu-bundle dev-master (838c4a0 => e5700ed) Checking out e5700ed8cbd5c402d24d6dda118aa23400937288

**Comment by matthbull** [comment]
I had this same issue and @Stof was right, I was using a custom template (a badly written one) where the `safe_label` flag hadn't been catered for.

**Comment by cirovargas** [comment]
Im trying to use safe labels with a custom template (copyed and little modifications):

`    {{ knp_menu_render('CoreAdminBundle:Builder:admin', {'currentClass': 'active','allow_safe_labels ':true, 'template': 'CoreAdminBundle:Menu:knp_menu_admin.html.twig'}) }}`

The option go to helper render function (Knp\Menu\Twig\Helper::render), print_r:
```
                        Array
    (
        [currentClass] => active
        [allow_safe_labels ] => 1
        [template] => CoreAdminBundle:Menu:knp_menu_admin.html.twig
    )
```

but in the template the option goes false:
`{{ dump(options.allow_safe_labels) }}`

What's wrong?

**Comment by bopoda** [comment]
I use the default templates.

**render menu in .twig:**
<pre>
{{ knp_menu_render('AppBundle:Builder:navBarMenu', {'allow_‌​safe_labels': true})|raw }}
</pre>
**Menu Builder:**
<pre>
$menu = $factory->createItem('root', [
    'childrenAttributes' => [
        'class' => 'nav navbar-nav navbar-right',
    ],
]);
$menu->addChild('title', [
    'uri' => '#',
    'label' => 'title<span class="caret"></span>',
    'extras' => ['safe_label' => true]
]);
</pre>

I just want to add `<span class="caret"></span>`, but it is still escaping http://joxi.ru/p2764gKSoLyy8m .
Could someone help please?

**Comment by bopoda** [comment]
Sorry, it works at the moment. 
i copied strings and seems it was hidden characters in allow_safe_labels option... http://joxi.net/5mdNBG4skJ6jqA
