### ISSUE TITLE
Add a child with an anchor link

### ISSUE THREAD

**Issue by drskullster** [KnpLabs/KnpMenuBundle#245]
Hi,

How can I do to generate a route with an anchor link ?

As stated by Fabien Potencier, there's no parameter built in to generate anchor links. He advises to concatenate the string at the end of a generated url : https://github.com/symfony/symfony/issues/3910#issuecomment-5110238

I couldn't find a way to pass a generated url to the `addChild` method .

```
$menu->addChild('Tutos', array('route' => 'my_route_name'));
```

Does anybody know a way to achieve that ?

**Comment by jstgermain** [comment]
this is great if you want to type the uri instead of it automatically doing it from the route, so this solution is sort of halfassed IMO. Is there not a way to use the route and have it render the hashtag? I personally would prefer to just handle the pattern in the route and call route for the menu rendering... pattern:       /products.html#broker-solutions

**Comment by christopherlouet** [comment]
You can generate the URL with the router if you want the good path in environnement developpement.

The constructor :
```
/**
     * @param FactoryInterface $factory
     * @param UrlGeneratorInterface $router
     */
    public function __construct(
    		FactoryInterface $factory,
    		UrlGeneratorInterface  $router
    		)
    {
        $this->factory = $factory;
        $this->router = $router;
    }
```
The method to generate menu :
```
/**
     * @param array $options
     * @return \Knp\Menu\ItemInterface
     */
    public function createHomeMenu(array $options)
    {
    	$uri = $this->router->generate("home");
        $menu = $this->factory->createItem('root');
    	
    	$menu->addChild('menu.services', array('uri' => $uri.'#services'));
    	$menu->addChild('menu.products', array('uri' => $uri.'#products'));
    
    	return $menu;
    }
```

**Comment by c33s** [comment]
for reference and googlers: 

```php
$menu->addChild('my label', ['route' => 'my_route', 'routeParameters' => ['_fragment' => 'my_anchor']]);
```
