### ISSUE TITLE
Thoughts regarding the new "best practices"

### ISSUE THREAD

**Issue by DougHayward** [KnpLabs/KnpMenuBundle#248]
Have recently installed Symfony2.6 and then decided to read the Best practices guide.
Now I know quite early on "do not refatctor your project to meet these standards" or something along those lines, but I just couldn't help myself (oops).

Since then I have started looking at incorporating the knp menu bundle, and have noticed the guide does not follow the new "AppBundle" spec I was wondering if it is something you would be interested in adding.

If so I don't mind doing it.

**Comment by stof** [comment]
remaining places have been converted to AppBundle in #255
