### ISSUE TITLE
hinclude and active item

### ISSUE THREAD

**Issue by patie** [KnpLabs/KnpMenuBundle#250]
Hi,

knpmenu bundle works great, but i have problem when using hinclude (refreshing partial view in browser)

its normal because hinclude in symfony2 calling url /_fragment... so knpmenu bundle dont know from this url which navigation item is active/current.. any idea how can solve this please ? thx

**Comment by patie** [comment]
you right, but i cannot find tutorial for this, in documentation are few lines who do not adequately explain imho :/

**Comment by stof** [comment]
Create a service implementing the VoterInterface of KnpMenu, and tag it with the ``knp_menu.voter`` tag. The doc about this is indeed missing. It is referenced by https://github.com/KnpLabs/KnpMenuBundle/issues/236

**Comment by patie** [comment]
i can try it again, thx

**Comment by WouterJ** [comment]
Closing as this issue can be fixed by a custom voter, as explained by @stof. I hope you figured out how to do it! (please note that voters are now documented in the KnpMenu library)
