### ISSUE TITLE
Suggest making the trans filter standard instead of having to extend the knp_menu.html.twig

### ISSUE THREAD

**Issue by jenswegar** [KnpLabs/KnpMenuBundle#252]
Given that all apps these days should be prepared for translation from the get go, I'm wondering if it would be any idea to simplify the translation process of menu items by adding the trans filter to the default knp_menu.html.twig instead of the developer having to extend the default template just to add translation support? Or is there a technical/design reason it's not part of the default template? Afaik there really is no performance penalty since the menu is cached in production anyway?

**Comment by Nek-** [comment]
:+1:

**Comment by jenswegar** [comment]
hmm, I can understand that to some extent. On the other hand, the fix is two lines of code in a new template file (as per documentation), so not sure how much extra maintenance that would require in the end...

**Comment by WouterJ** [comment]
I think we should include this. This would mean creating a template in this bundle and doing:
```jinja
{% extends 'knp_menu.html.twig' %}

{% block label %}{{ parent()|trans(...) }}{% endblock %}
```

/cc @dbu @stof

**Comment by dbu** [comment]
and then having a configuration to use the translating template instead? and configure the translation domain? either that, or just put what you said above into the documentation, it seems easy enough to let the users do this

**Comment by WouterJ** [comment]
@dbu why not simply do this by default, using a `knp_menu` domain? Forms, Validators, Security, etc. all include translation by default as well.

**Comment by stof** [comment]
@WouterJ there is no reason to use a knp_menu domain: we won't provide any translations

**Comment by stof** [comment]
and we cannot use the trans filter in the default theme in KnpMenu as this would force a hard-dependency on the trans filter in the library, making the library unusable for anyone else (at least the Twig integration)

**Comment by dbu** [comment]
the forms or validation also don't provide translations for form labels or validation error messages. so why not. there is an overhead involved for untranslated menu but if form and validation can do that by default without too many problems, we can probably also do the same

**Comment by dbu** [comment]
right, we don't want this in the library. but wouter proposed to do it in the bundle where we would have symfony and translations anyways.

**Comment by stof** [comment]
@dbu and form labels are **not** translated in a custom domain. there is no ``forms`` translation domain in Symfony. And regarding the validator and security messages, they are precisely providing translations for all builtin  authentication failures and validation constraints.
