### ISSUE TITLE
children of block "listList" are missing a surrounding ul-tag

### ISSUE THREAD

**Issue by bitladen-nw** [KnpLabs/KnpMenuBundle#267]
hi.

when rendering a menu like 

- product
  - category1
     - category2

the second level menu (category2) is missing a surrounding ul tag. 

i assume this is a bug which can be fixed by modifying 

```
{% block listList %}
{% spaceless %}
    {% if item.hasChildren and options.depth is not sameas(0) and item.displayChildren %}
        {{ block('children') }}
    {% endif %}
{% endspaceless %}
{% endblock listList %}
```

to 

```
{% block listList %}
{% spaceless %}
    {% if item.hasChildren and options.depth is not sameas(0) and item.displayChildren %}       
       <ul{{ _self.attributes(listAttributes) }}>
            {{ block('children') }}
       </ul>
    {% endif %}
{% endspaceless %}
{% endblock listList %}
```

**Comment by stof** [comment]
There is no block ``listList`` in KnpMenu templates. So thins looks related to a custim template you are using.

**Comment by bitladen-nw** [comment]
right. it's the bootstrap template from braincrafted bootstrap-bundle... sorry, you are the wrong addressee...
