### ISSUE TITLE
Impossible to put 2 times the same item in a menu

### ISSUE THREAD

**Issue by nykopol** [KnpLabs/KnpMenuBundle#274]
I would like to put 2 identical items in the same menu. But only the first one is rendered.
It appends when the labels and the routes are the same. 

I know that  it's not common to put 2 times the same item in one menu but in my case it make sense. (a big menu with the same functionality accessible thru different submenu)

**Comment by stof** [comment]
Are you using only the same label and route or also the same item name ? the item name identifies a child item, so if you reuse the same, it replaces the previous item with the same name.

**Comment by stof** [comment]
note that item names are only unique among their parent, not among the whole tree

**Comment by nykopol** [comment]
Thanks for your help. I didn't notice the name identifier. I was using only label and routes. With the name it work perfectly.
