### ISSUE TITLE
Language switcher in Menu (Builder)

### ISSUE THREAD

**Issue by JHGitty** [KnpLabs/KnpMenuBundle#288]
I want to add a language switcher to the menu.

In Twig I could do:
```twig
<a href="{{ path(app.request.get('_route'), app.request.get('_route_params')|merge({'_locale': 'fr'})) }}">Test</a>
```

But how to do it in the menu builder?

**Comment by jonny827** [comment]
@JHGitty  Is this what you are looking for?

`$menu->addChild('Test', array('route' => 'test', 'routeParameters' => array('_locale' => 'fr')));`

Modified an example in the doc's found [here](https://github.com/KnpLabs/KnpMenuBundle/blob/master/Resources/doc/index.rst) to meet your needs.
