### ISSUE TITLE
Error Trying to install with Symfony 3

### ISSUE THREAD

**Issue by chinmayshah24** [KnpLabs/KnpMenuBundle#292]
`composer require knplabs/knp-menu-bundle "~2"`

"The package is not available in a stable-enough version according to your minimum-stability setting"

**Comment by stof** [comment]
the Symfony3-compatible version of the bundle is not yet released. You need to allow dev versions of the bundle for now.
Expect it to change soon, as I plan to release stable versions of the packages I maintain in the next few days (but the SymfonyCon will keep me busy tomorrow and on Friday and Saturday, so it may have to wait until Sunday)

**Comment by JHGitty** [comment]
@stof Could you release a Symfony3-compatible version?

**Comment by dbu** [comment]
looking at https://github.com/KnpLabs/KnpMenuBundle/compare/v2.1.0...master i think we could tag v2.1.1 right now, there are no changes in the code, only the composer.json change for symfony 3 and some testing and documentation fixes.

@JHGitty can you confirm the dev version works in your application with symfony 3.0?

**Comment by JHGitty** [comment]
@dbu Sure, I already use KnpMenuBundle in some Symfony 3 projects.
(Is there any other bundle for menus? I only know KnpMenu :+1: )

**Comment by dbu** [comment]
there we go: https://github.com/KnpLabs/KnpMenuBundle/releases/tag/v2.1.1

**Comment by stof** [comment]
@dbu you forgot to update the changelog.md file

**Comment by dbu** [comment]
argh. sorry. what do? just update it in master? i guess its not worth to do a new tag just for that? and i learned that changing what commit a tag points to is really not cool for automated systems...

**Comment by stof** [comment]
yeah, update it in master only (but remember to do it before tagging for next times). Redoing a release just for that is not worth it (code is not broken)

**Comment by dbu** [comment]
ff3434782588fa371adf8361f5d2e9fd162d5508 - trying to remember next time
