### ISSUE TITLE
Lacking documentation about defining a Matcher for the twig default renderer

### ISSUE THREAD

**Issue by xDaizu** [KnpLabs/KnpMenuBundle#294]
I'm having trouble setting the "current" item of a Menu. I know how to implement my own Voter as service, , I've done it in the past but I'd like to use the default voters included in KnpMenu.

I feel like there's already a way to configure which Matcher you want to use for the default Twig renderer, but I can't find it, and the documentation largerly ignores this matter or uses deprecated method like setCurrentUri() [i.e. here](http://symfony.com/doc/master/bundles/KnpMenuBundle/events.html) (first snippet, line 16) or imples it does it [automagically](http://symfony.com/doc/master/bundles/KnpMenuBundle/index.html#method-a-the-easy-way-yay)..... which it doesn't ^^U

Any orientation would be appreciated. Once understood, I could document it myself.

**Comment by stof** [comment]
We use a single matcher, with multiple voters registered in it. So no, there is no way to configure the matcher you use, as there is no way to have multiple matchers.

**Comment by xDaizu** [comment]
Ok, I understood that, but is it supposed to be called by default? Or is it dependent on any parameter for the base uri or something like that. Because I have s very simple menu, where, for every child I define a label and a uri and no item gets the "current" class. It gets the "first" and "last" class, though.

I know this section is no QA, but this code should work, shouldn't it? Am I missing any "gotchá"?

     $menu = $this->factory->createItem('root');
     foreach ($apps as $app) 
        {
         $child = $menu->addChild($app->getShortname(), array(
                'uri' => $app->getUri(),
                'label' => $app->getName(),
            ));
           $child->setAttribute("class", $child->getAttribute("class") . " item");
           }
        return $menu;

**Comment by stof** [comment]
In the bundle, only the route-based voter is registered by default. As your item does not have an associated route, there is no match.
What you would need is registering a voter for your case

**Comment by xDaizu** [comment]
Thanks! That's what I wanted to know, and couldn't find documented anywhere! :D
Now, is there an "official way" of adding a URI voter to the default Twig Renderer Matcher? Should be easy. 

In case of it not being that easy (or advisable), what would be the "correct"/recommended/mantainable way of overriding the default twig renderer Matcher, so I can add a custom Matcher with the default URI voter added?

**Comment by stof** [comment]
Just tag your service with ``knp_menu.voter`` and it will be registered

**Comment by xDaizu** [comment]
Just tagging it? Like this? 

    services:
        app.menu_builder:
            class: License\AppBundle\Menu\MenuBuilder
            arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager", "@router"]
            tags:
                - { name: knp_menu.menu_builder, method: createMainMenu, alias: top_menu }
                # The alias is what is used to retrieve the menu

        app.menu.voter.request:
            class: Knp\Menu\Matcher\Voter\UriVoter
            arguments:
                - @service_container
            tags:
                - { name: knp_menu.voter }

'cause that didn't work :(

**Comment by stof** [comment]
Closing this old issue. I suspect a configuration issue for the voter, as my own custom voters are working fine.
Btw, in the comment just above, injecting the container itself into the UriVoter does not make any sense.
