### ISSUE TITLE
Update description to Symfony(3)

### ISSUE THREAD

**Issue by JHGitty** [KnpLabs/KnpMenuBundle#295]
In the description of the KnpMenuBundle on GitHub there is:
```
Object Oriented menus for your Symfony2 project
````

I think it should be changed to ``Symfony``.

**Comment by dbu** [comment]
:+1: - can you do a pull request? simply use the online editing.

**Comment by JHGitty** [comment]
I think only the maintainers on GitHub can update the git repository description on GitHub.
Here you can see it: https://github.com/KnpLabs/KnpMenuBundle

@dbu Could you update it?

**Comment by dbu** [comment]
it seems my privileges do not reach that far. paging @stof

**Comment by stof** [comment]
Done
