### ISSUE TITLE
Error on using "knp_menu_render" in template

### ISSUE THREAD

**Issue by ghost** [KnpLabs/KnpMenuBundle#303]
An exception has been thrown during the rendering of a template ("You have requested a non-existent service "request". Did you mean one of these: "monolog.logger.request", "request_stack", "assetic.request_listener", "router.request_context", "data_collector.request"?") in XXX::base.html.twig at line 18. 

I tried with latest stable Version and also with dev-master - but nothing work. Cleared Cache several times. Can you Help me?

**Comment by yasasn86** [comment]
I also have the same issue

**Comment by pesseyjulien** [comment]
Same error after upgrading to symfony 3 and sensio distribution 5 :

`An exception has been thrown during the rendering of a template ("You have requested a non-existent service "request". Did you mean one of these: "router.request_context", "request_stack", "addict_web.bundle.menu.voter.request", "monolog.logger.request", "assetic.request_listener", "fos_rest.request.param_fetcher.reader", "fos_rest.request.param_fetcher", "data_collector.request"?") in AddictWebBundle:Menu:knp_menu.html.twig at line 20.
`

**Comment by diegograssato** [comment]
I also have the same issue.

**Comment by WouterJ** [comment]
I tried reproducing this locally, but I don't get any error on Symfony 3. I also can't find any dependency on the `request` service in this bundle.

Which version of this bundle do you use (`composer show -i | grep knplabs/knp-menu`)? And did you customize anything (e.g. add a custom voter?)?

**Comment by pesseyjulien** [comment]
This is my version :

```
knplabs/knp-menu                     v2.1.1             An object oriented ...
knplabs/knp-menu-bundle         dev-master     3cee352
```

And no custom voter on my side.

**Comment by DamienChiboub** [comment]
Same message with Knp_Paginator_Bundle on Symfony 3.0.2 : 

knplabs/knp-components               1.3.2              Knplabs component library
knplabs/knp-paginator-bundle         2.5.1              Paginator bundle

**Comment by WouterJ** [comment]
Is it maybe possible for someone to fork the [standard edition](http://github.com/symfony/symfony-standard) and add the most minimal example to reproduce this error? I've tried some things, but I'm unable to get this error on Symfony 3.

**Comment by J-who** [comment]
I came across this issue when I was trying to reuse some code from another project in a new 3.0 project.

I was using a RequestVoter
```
services.yml

    menu.voter.request:
        class: AppBundle\Menu\RequestVoter
        arguments:
            - "@service_container"
        tags:
            - { name: knp_menu.voter }
```

And in the RequestVoter.php file I was using:
`$this->container->get('request')->getRequestUri()`

I changed this to
`$request = $this->container->get('request_stack')->getCurrentRequest();`
`$request->getRequestUri()`

Hopefully this helps someone.

**Comment by pesseyjulien** [comment]
Great, thanks @J-who !

**Comment by WouterJ** [comment]
Please note that if you add a `setRequest` method in your voter, you can use `- { name: knp_menu.voter, request: true }` and the `setRequest` will be called each time the request scope changes.

**Comment by WouterJ** [comment]
I'm going to close this issue as I still don't believe this project causes the bug. If someone can provide more information, a project to reproduce the bug, etc., please share it in a comment and I'll reopen the issue.
