### ISSUE TITLE
How to add FontAwesome icons inside links ?

### ISSUE THREAD

**Issue by eved42** [KnpLabs/KnpMenuBundle#306]
Hi everyone,

is it possible to add something in `<a></a>` tags other than label ?
I would like to add FontAwesome icons like this (`<i></i>` tags before label) : 

`<li class="current first"><a href="/" title="Home"><i class="fa fa-home"></i> Home</a></li>`

Thanks.

**Comment by WouterJ** [comment]
There are a couple ways to achieve this:

 * Put the HTML code directly in the label and set `allow_safe_labels` to true in the renderer options and `safe_label` to `true` in the menu node extra's
 * Extend the default template and use an `icon` extra option for menu nodes to specify the icon:

   ```jinja
   {% extends 'knp_menu.html.twig' %}

   {% block label %}
    {% if item.getExtra('icon') %}
        {# the item has the 'icon' extra set, display the FA icon #}
        <i class="fa fa-{{ item.getExtra('icon') }}"></i>
    {% endif %}

    {# render the span/link element #}
    {{ parent() }}
   {% endblock %}
   ```

**Comment by eved42** [comment]
I don't understand very well, I followed Symfony documention and I've tried this : 

In the menu Builder.php
`$menu->addChild("exit", array(
         'route' => 'ep_logout',
         'label' => "<i class='fa fa-close'></i> Exit",
         'safe_label' => true
      ));`

In my twig html file
`{{ knp_menu_render('AppBundle:Builder:mobilePrivateMenu', {'allow_safe_labels': true}) }}`

But it doesn't work... Can you help me ?

**Comment by WouterJ** [comment]
Use:
```php
$menu->addChild("exit", array(
    'route' => 'ep_logout',
    'label' => "<i class='fa fa-close'></i> Exit",
    'extras' => array('safe_label' => true),
));
```

**Comment by eved42** [comment]
Thanks !
