### ISSUE TITLE
Menu/Builder with container

### ISSUE THREAD

**Issue by Pierstoval** [KnpLabs/KnpMenuBundle#312]
In [BuilderAliasProvider.php#L122](https://github.com/KnpLabs/KnpMenuBundle/blob/dddaec754e7edd004f3c964c33c2eb5903f5ffdb/Provider/BuilderAliasProvider.php#L122), `ContainerAwareInterface` is checked but not `ContainerAwareTrait`.

Since using `ContainerAware` solely is deprecated, and that traits cannot implement interfaces, it would be sad to force the user to *both* use the trait and implement the interface.

Is there a BC solution to set the container automatically for menus using only `ContainerAwareTrait` and not `ContainerAwareInterface`?

**Comment by WouterJ** [comment]
> Since using ContainerAware solely is deprecated, and that traits cannot implement interfaces, it would be sad to force the user to both use the trait and implement the interface.

I wouldn't call it sad. Interfaces are the only "contracts" in OO world. Only an interface should inform other classes about the available public API. Traits are just little helpers imo, they shouldn't replace interfaces.

So I'm -1 on including this feature in this bundle, sorry.

**Comment by Pierstoval** [comment]
So you suggest to use both trait AND interface?

**Comment by WouterJ** [comment]
Yes. Trait is a helper to not duplicate code, interface is the contract with the outside world to tell about the available methods.

**Comment by Pierstoval** [comment]
I did not thought the concept was so different with traits, so I'll close this issue and review my code ;)
