### ISSUE TITLE
fail to add extension to knp_menu.factory service

### ISSUE THREAD

**Issue by bpetitcollot** [KnpLabs/KnpMenuBundle#321]
i try to use KnpMenuBundle (2.0) with CMFMenuBundle (2.0) but ContentExtension is ignored by the menu factory.

while knp_menu.factory appears when i call debug:container, it seems that knp_menu.factory is not loaded at compilation time :
`var_dump(array_keys($container->getDefinitions()));exit;`
added at first line of AddExtensionsPass::process gives no knp_menu.factory key.

If i change the id of knp_menu.factory in menu.xml, the service is loaded (the key is in my dumped array)

**Comment by bpetitcollot** [comment]
Well, my mistake, KnpMenuBundle was registered after CmfMenuBundle in my kernel and had to be placed before. It works fine now.

**Comment by dbu** [comment]
ah, glad you found it! we recently fixed the problem but there have been no new releases. once we release new versions of knp menu bundle and cmf menu bundle, the order will no longer cause problems.
