### ISSUE TITLE
labels are not translated

### ISSUE THREAD

**Issue by csiewert** [KnpLabs/KnpMenuBundle#322]
Hey,

for some reasons my menu labels are not translated by default:

    public function mainMenu(FactoryInterface $factory, array $options)
    {
        $menu = $factory->createItem('root');

        $menu->addChild('messages.foo', array('route' => 'bar'));

        return $menu;
    }

_messages.en.yml_:

    messages.foo: bar

If I use 

    {% trans %}messages.foo{% endtrans %}

somewhere else in my templates, the string is translated correctly. 

_php app/console debug:translation en_ gives me the following:
    
    messages messages.foo bar

I'm using _symfony 2.7.14_ and _knpmenubundle 2.1_.

Any suggestions?

Best
Christian

**Comment by csiewert** [comment]
I noticed in the corresponding template from knpmenu:

    {% block label %}
        {% if options.allow_safe_labels and item.getExtra('safe_label', false) %}
            {{ item.label|raw }}
        {% else %}
            {{ item.label }}
        {% endif %}
    {% endblock %}

Where comes the translation in?

**Comment by dbu** [comment]
there is https://github.com/KnpLabs/KnpMenuBundle/blob/master/Resources/views/menu.html.twig which looks like it would translate. but maybe one of the refactorings broke something?

**Comment by dbu** [comment]
where do you find that label block?

**Comment by csiewert** [comment]
hmm....I got that file from vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views. I'm using 2.1 of the bundle and in that version, there isnt a views directory in the vendor/knplabs/knp-menu-bundle/Resources directory.

Is there something broken?

For now I'm overriding the label block which works fine for me:

    {% block label %}
        {{ item.label|trans }}
    {% endblock %}

**Comment by dbu** [comment]
ups, looks like there was never a release with that file. will check if we could tag a release soonish.

**Comment by csiewert** [comment]
Ok, thank you.

**Comment by dbu** [comment]
tagged 2.1.2 with this fix included.

**Comment by csiewert** [comment]
Thank you, I updated composer. How do you extend that specific file in twig?

    {% extends 'knp_menu.html.twig' %} 

is extending Knp/Menu/Resources/views and not knp-menu-bundle/Resources/views.

Thank you anyway. :+1:

**Comment by dbu** [comment]
if you use full stack symfony, i think you should specify the file as KnpMenuBundle::menu.html.twig

**Comment by dbu** [comment]
note that the file is called menu.html.twig, not knp_menu.html.twig

**Comment by csiewert** [comment]
Ah ok, that worked for me. Thank you very much.
