### ISSUE TITLE
Item aren't translated

### ISSUE THREAD

**Issue by mysterty** [KnpLabs/KnpMenuBundle#324]
Hello,

I'm following the Sf3 doc here: http://symfony.com/doc/current/bundles/KnpMenuBundle/i18n.html

It says that translation should be auto and allow to specify domain.
But in fact, the bundle call knp_menu.html.twig from KnpMenu and not the one from KnpMenuBundle and don't handle translation :
`{% block label %}{% if options.allow_safe_labels and item.getExtra('safe_label', false) %}{{ item.label|raw }}{% else %}{{ item.label }}{% endif %}{% endblock %}`

**Comment by dbu** [comment]
we fixed something about that in https://github.com/KnpLabs/KnpMenuBundle/releases/tag/2.1.2 - are you using that version of the bundle?

**Comment by mysterty** [comment]
Yes, i'm using it, but it's not this template from KnpMenuBundle wich is used but the template from KnpMenu.

Maybe i do something wrong ?

**Comment by dbu** [comment]
could it be that you have a configuration for the template that overrides the default? https://github.com/KnpLabs/KnpMenuBundle/blob/master/DependencyInjection/Configuration.php#L39

**Comment by mysterty** [comment]
You are right, it's when i follow that step of the doc : http://symfony.com/doc/current/bundles/KnpMenuBundle/index.html#step-3-optional-configure-the-bundle

Maybe it could be usefull to explain that point a little bit more... ? I have to say that i don't really understand what this configuration does...

**Comment by dbu** [comment]
oh, that doc is outdated. i will try to send a PR to update it to the
new default.

as a general rule: don't copy default configuration into your
configuration ;-) only put the things you need to overwrite...
