### ISSUE TITLE
KnpMenu updated : RouteVoter no more autoloaded.

### ISSUE THREAD

**Issue by jorismulliez** [KnpLabs/KnpMenuBundle#330]
Hi, 

I just update my symfony App via composer.
And I got this error after the update : 

> An exception has been thrown during the rendering of a template ("The matcher must be set to get the current item of a menu") in MyBundle::layout.html.twig at line 49. 

Here is the line of knpmenubundle in my composer.json : 

```
 "knplabs/knp-menu-bundle": "^2.1",`
```

And the line pointed by the error is : 

``` twig
{% set breadcrumbArray = knp_menu_get_breadcrumbs_array(knp_menu_get_current_item('MyBundle:Builder:topMenu')) %}
```

I looked into composer.lock to see if KnpMenuBundle was udpated, but it appear to be KnpMenu itself.
So I don't know if the issue is related to KnpMenu or to the integration of KnpMenu into KnpMenuBundle.

I can read here : https://github.com/KnpLabs/KnpMenu/blob/master/doc/05-Matcher.md#create-your-own-voters that matcher is configured automatically by KnpMenuBundle.

So how can I build my breadcrumb with this KnpMenu release ?
What I'm doing wrong ?

Thanks for your help,

**Comment by stof** [comment]
The matcher is set as of https://github.com/KnpLabs/KnpMenuBundle/pull/251 so I'm closing this old issue.
