### ISSUE TITLE
Could not render CnertaBreadcrumb with KnpMenuBundle Allways Returns root

### ISSUE THREAD

**Issue by Van-peterson** [KnpLabs/KnpMenuBundle#331]
{{ cnerta_breadcrumb_render('main', {'template': 'AfreakModuleBundle:Breadcrumb:myBreadcrumb.html.twig'}) }}
I always get "root" as breadcrumb on every page after upgrading to dev-master both bundle

**Comment by stof** [comment]
I have no idea what the ``cnerta_breadcrumb_render`` method is. You should ask support to the package providing it

**Comment by benrcole** [comment]
I posted previously on [StackOverflow ](http://stackoverflow.com/questions/41304270/can-you-make-knpmenu-voters-private) with what I think could be a similar problem. It seems to be that any service tagged as a `Voter` is used for any `Menu` that is built within your Symfony app.

I use the `SonataAdminBundle` in my app and that adds a [ChildrenVoter](https://github.com/sonata-project/SonataAdminBundle/blob/master/Menu/Matcher/Voter/ChildrenVoter.php) which returns true if the Child of any Menu item is active - this forces `knp_menu_get_current_item()` to always return the root of the tree

I know there is a way to set the priority of `Voters` Is it possible to remove or restrict `Voters` for specific menus?

**Comment by stof** [comment]
Well, you should open an issue on SonataAdminBundle to ask them to change their voter to avoid breaking menus they don't own (by restricting votes based on something they put in the menu)

**Comment by benrcole** [comment]
OK, 

If I wanted to remove one of the default voters from the KnpMenuBundle, is the correct way via bundle overriding?

**Comment by stof** [comment]
dedicated to what ?

**Comment by greg0ire** [comment]
@stof dedicated to disambiguising a menu and associating by associating it with a lib. But maybe libs that create menus are not that common for it to be worth it?

**Comment by stof** [comment]
@greg0ire but then, you would have to ensure that all child items have this same setting, and so on.

Btw, I think the Sonata behavior is just totally useless. They would just need to use the KnpMenu feature allowing to render a specific class for ancestors of a current item (what they do is making all ancestors current as well, and then using a class only for the current elements)

**Comment by greg0ire** [comment]
> They would just need to use the KnpMenu feature allowing to render a specific class for ancestors of a current item

I didn't know about this feature. @andrey1s , you implemented the voter, could you please replace it with that?

**Comment by stof** [comment]
I'm closing this issue, as the bug comes from a bad behavior in SonataAdminBundle (and there is a PR referenced just above with a fix)
