### ISSUE TITLE
items created by createDropdownMenuItem are not translated

### ISSUE THREAD

**Issue by iv-enovation** [KnpLabs/KnpMenuBundle#334]
In MenuBuilder.php:
$dropdown = $this->createDropdownMenuItem($menu, "Manage plugins", false, array('caret' => true));

In app/Resources/translations/messages.fr.yml:
Manage plugins: Gérer les plugins

**Comment by stof** [comment]
There is no ``createDropdownMenuItem`` in this bundle, so I cannot help you
