### ISSUE TITLE
Error "Accessing Twig_Template attributes is forbidden"

### ISSUE THREAD

**Issue by MyTheValentinus** [KnpLabs/KnpMenuBundle#335]
Hello,
I have this error when i render menu.
Due of modifications of twig in 2.10 version with import function ? KnpMenuBundle use import function.
How to fix this ?
Thanks

https://pic.valentin.ovh/21.01.17-20-49-45.png

**Comment by pierregaste** [comment]
@MyTheValentinus same here! How do you fix it please?

Thanks for your answer!

**Comment by MyTheValentinus** [comment]
In my template i move macro import.

**Comment by ducho** [comment]
Hi @MyTheValentinus  !
I have same problem. Where did you move macro import? Thanks.
