### ISSUE TITLE
Documentation Clarity: Complex Translation Structure

### ISSUE THREAD

**Issue by BallisticPain** [KnpLabs/KnpMenuBundle#338]
I think it would be handy if the documentation described a more complex and likely widely used set of examples for translating menu items.

I have started a PR for this. Just wanted a ticket to reference.

Please let me know if anyone agrees... PR with Details: #337

I don't know the XLF format so if someone could inform me here or attach it to the PR, I would love for this to be feature complete.

**Comment by stof** [comment]
Translations are using the Symfony feature. So any documentation about writing translation files is found in the official Symfony documentation. I have no reason to duplicate it in this bundle (where it does not belong, and would not be updated by the Symfony doc team)
