### ISSUE TITLE
Issues with templates using bundle notation

### ISSUE THREAD

**Issue by javiereguiluz** [KnpLabs/KnpMenuBundle#355]
As reported in https://github.com/symfony/symfony-demo/issues/652, there could be issues with this bundle in modern Symfony 3.3+ applications using Symfony Flex. I don't know this bundle, so I can't provide the exact solution, but this is how this could be solved:

1) If you use bundle notation for templates (e.g. `KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig`) you must add `symfony/templating` to `require` instead of `require-dev` in composer.json.
2) If you can change the template notation (and docs), you should replace `KnpPaginatorBundle: ... : ....html.twig` by `@KnpPaginator/.../....html.twig`  This modern Twig namespace notation doesn't require `symfony/templating` and it works in old and new Symfony applications.

**Comment by stof** [comment]
I think you should also report this to KnpPaginatorBundle as the example you gave comes from here 😄

**Comment by TNAJanssen** [comment]
Yes, also having the same issue, can I help with solving it?

**Comment by stof** [comment]
Closing this as #357 changed the default template in the bundle to avoid this issue in this bundle (not released yet, but will come soon)
