### ISSUE TITLE
require twig

### ISSUE THREAD

**Issue by ElectricMaxxx** [KnpLabs/KnpMenuBundle#359]
As `framework-bundle` removes templating component from version 3.2 on, you should require twig, as your service `knp_menu.renderer.twig` requires it by default.

**Comment by ElectricMaxxx** [comment]
@dbu we (you) should hae push access here, right?

**Comment by dbu** [comment]
added a note in #358 which is about symfony 3.3 support of this bundle

**Comment by dbu** [comment]
@ElectricMaxxx is this solved with #358 being merged?

**Comment by stof** [comment]
Well, if you don't use Twig at all, you can use the `list` renderer instead of the `twig` one, which does not have any dependency except KnpMenu (but is less configurable than the twig one)

**Comment by ElectricMaxxx** [comment]
I think i opened it cause the instellation test of our menu-bundle failed, so i will try it again tomorrow.
