### ISSUE TITLE
Refactor to work with twig directly when the templating component is not used

### ISSUE THREAD

**Issue by dbu** [KnpLabs/KnpMenuBundle#374]
as said in #372: This bundle needs a bugfix to properly register the path in case Twig is used without using the Templating component.

**Comment by codedmonkey** [comment]
Is there a particular reason this bundle uses `twig.loader.filesystem` instead of `twig.loader.native_filesystem`? It seems that could easily circumvent the Templating dependency entirely since that one is included in the Twig bundle. During my short debugging it worked fine.
