### ISSUE TITLE
Override the getBuilder method

### ISSUE THREAD

**Issue by QuentinCurtet** [KnpLabs/KnpMenuBundle#386]
Hi,

I just wanted to override the getBuilder method in order to put my builder in another folder than MyBundle\Menu, but i realize that it's not possible.

Is it possible to make the variables $kernel, $container and $menuFatcory protected so the overwrite could be possible ?

Thanks in advance.

**Comment by stof** [comment]
`getBuilder` of which class ?

**Comment by QuentinCurtet** [comment]
Oh sorry, i think i precised it ^^
This one : https://github.com/KnpLabs/KnpMenuBundle/blob/master/src/Provider/BuilderAliasProvider.php

**Comment by stof** [comment]
Well, if you want to define builders elsewhere, my suggestion is to define builders as services instead of relying on this BuilderAliasProvider: http://symfony.com/doc/master/bundles/KnpMenuBundle/menu_builder_service.html

**Comment by QuentinCurtet** [comment]
In fact, this provider does what i want perfectly except the path of the Builder class to render to the twig method knp_menu_render.
That's why i just wanted to override this to change the path, or it would be nice to update the knp_menu_render to add the path in arguments.
