### ISSUE TITLE
[SF4] Container is null into Builder.php

### ISSUE THREAD

**Issue by mysterty** [KnpLabs/KnpMenuBundle#388]
Hello,

I installed knp_menu_bundle as described in the doc.

I use it as service as it's needed in SF4.

I `use ContainerAwareTrait;`

But if i try to call container as described in the doc for geting entityManager, i get :
```PHP
$em = $this->container->get('doctrine')->getManager();
// returns : Call to a member function get() on null
```

Did i forgot something or is ContainerAwareTrait incompatible with SF4 ?

**Comment by stof** [comment]
Are you implementing the ContainerAwareInterface ? Using the trait is not what is detected by the bundle (as traits don't exist at runtime). The trait is handy to implement the needed method of the interface for you, but you still need to mark your class as implementing the interface.

**Comment by mysterty** [comment]
@stof Yes, i'm using it exactly as the doc says :
```PHP
use Knp\Menu\FactoryInterface;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerAwareTrait;

class Builder implements ContainerAwareInterface
{
    use ContainerAwareTrait;
    // ...
}
```

Note that for quick fixing it, i just pass container interface to the service, but it still not according the documentation :
```
app.menu_builder:
        class: App\Menu\Builder
        arguments: ["@knp_menu.factory", "@service_container"]
```

**Comment by stof** [comment]
hmm, for builders defined as a service, the bundle does not implement any special support for ContainerAwareInterface (all the instantiation is handled by the service definition).

And in your case, you are trying to inject the container in the constructor, not through `setContainer`

**Comment by mysterty** [comment]
In fact, we can only use the bundle through a service in V4.
So, maybe the bundle should be update for V4 or the doc should be updated ?

PS : I don't know the "setContainer" method.
