### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by core23** [KnpLabs/KnpMenuBundle#405]
Could you please tag a new release, so autowiring is possible (#385)

**Comment by mikemix** [comment]
I'm not going to wait anyway. You can require `"knplabs/knp-menu-bundle": "dev-master#1cb5ebae9e1892347eda155dc25e0bea57137b9e`

**Comment by ping-localhost** [comment]
@stof Can you please tag a new release? That way I can resolve a deprecation issue related to eaf23ad6a0f1fd028b7d6d5fb1ba2c5b56d31013

**Comment by core23** [comment]
Is this project dead @stof ?

**Comment by emodric** [comment]
Hi. Any news on release?

**Comment by mikemix** [comment]
Ping @stof

**Comment by core23** [comment]
@dbu Can you create a new release?

**Comment by dbu** [comment]
seems that i have the permissions: https://github.com/KnpLabs/KnpMenuBundle/releases/tag/2.2.2

and the changes looked reasonably safe to  me, so here we go...

**Comment by derrabus** [comment]
Thanks a lot, @dbu!
