### ISSUE TITLE
Menu (v2.2) does not fold open anymore in iOS13

### ISSUE THREAD

**Issue by xantos05** [KnpLabs/KnpMenuBundle#415]
I have noticed the KNP Menu does not open up anymore when using on an Apple device using iOS version 13.x. Happens in Safari and in Chrome so probably caused by the latest Apple updates. 

To be more exact. The menu does open (after a number of clicks) but it's very hard to select the right menu item. Most of the time the href on the main-menu item is being loaded.

Does anyone experiencing the same thing?

**Comment by stof** [comment]
What are you using to open menus ? KnpMenuBundle only provides tooling to render some HTML. It does not have any JS to open or close menus.

**Comment by xantos05** [comment]
I am using "mega-menu" to display the menu.
