### ISSUE TITLE
Add suport for Symfony 5

### ISSUE THREAD

**Issue by tacman** [KnpLabs/KnpMenuBundle#419]
Currently composer.json requires symfony framework 4.  

I'll follow the instructions at https://symfony.com/doc/current/contributing/code/pull_requests.html to contribute a PR.

**Comment by garak** [comment]
See PR #416

**Comment by tacman** [comment]
Can you tag a version that includes Symfony 5 support?  Otherwise, it seems like I have to see minimum-stability to dev, right?  Or is there another way?  version 3/master seems to work fine with Symfony5. Thanks.

**Comment by garak** [comment]
@tacman you can use our alias and require `^3.0@dev`. No need to alter your min stability

**Comment by tacman** [comment]
What does "use our alias" mean?  Put something in the repositories key of
composer.json?

**Comment by garak** [comment]
See https://github.com/KnpLabs/KnpMenuBundle/blob/master/composer.json#L38
You don't need anything other than the constraint with `@dev` suffix
