### ISSUE TITLE
Does not support Symfony 5.*

### ISSUE THREAD

**Issue by Unlik** [KnpLabs/KnpMenuBundle#421]
Restricting packages listed in "symfony/symfony" to "5.0.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - knplabs/knp-menu-bundle v2.3.0 requires symfony/framework-bundle ^3.4 | ^4.0 -> satisfiable by symfony/framework-bundle[v4.4.0] but these conflict with your requirements or minimum-stability.
    - knplabs/knp-menu-bundle v2.3.0 requires symfony/framework-bundle ^3.4 | ^4.0 -> satisfiable by symfony/framework-bundle[v4.4.0] but these conflict with your requirements or minimum-stability.
    - Installation request for knplabs/knp-menu-bundle ^2.3 -> satisfiable by knplabs/knp-menu-bundle[v2.3.0].

**Comment by GawainLynch** [comment]
Support for SF 5 went into `master` with #416, so until a new version is tagged you should just be able to require `"knplabs/knp-menu-bundle": "^3.0@dev"` in your root project.

**Comment by garak** [comment]
Released [v3.0.0](https://github.com/KnpLabs/KnpMenuBundle/releases/tag/v3.0.0)
