### ISSUE TITLE
Unknown "knp_menu_render" function.

### ISSUE THREAD

**Issue by Marcoparigi** [KnpLabs/KnpMenuBundle#435]
Symfony 5.1.6
Some users talked about clearing the cache but no effect for me.
Thanks for your help

**Comment by derrabus** [comment]
Could you give us some details on the actual problem, please?

**Comment by Marcoparigi** [comment]
Seems the twig function is not recognized as it should.
I have the same project in Symfony 4.3.4 version, and works well.

<img width="938" alt="Capture d’écran 2020-09-30 à 18 28 05" src="https://user-images.githubusercontent.com/2624344/94713180-c1463880-034a-11eb-8cde-e21ce5ee2e35.png">

**Comment by stof** [comment]
check your bundle configuration. Maybe you used `twig: false` in it to disable the Twig integration.

**Comment by Marcoparigi** [comment]
Nope because this parameter is not supported
<img width="504" alt="Capture d’écran 2020-09-30 à 19 08 10" src="https://user-images.githubusercontent.com/2624344/94717228-51d34780-0350-11eb-9e3d-5ae108353c69.png">

If i use the parameters described in step 3
[https://symfony.com/doc/current/bundles/KnpMenuBundle/index.html](url)

i got the following error message
<img width="933" alt="Capture d’écran 2020-09-30 à 19 12 00" src="https://user-images.githubusercontent.com/2624344/94717715-f81f4d00-0350-11eb-9e58-a5779db6afcc.png">

**Comment by stof** [comment]
this is not the configuration of `KnpMenuBundle` in your screenshot, but of `AdminLteBundle`

**Comment by Marcoparigi** [comment]
oups !! i never install the knp-bundle in my 5.1.6 !!!
My mistake, sorry ! It works ;)
