### ISSUE TITLE
New release for PHP 8 support

### ISSUE THREAD

**Issue by VincentLanglet** [KnpLabs/KnpMenuBundle#437]
The PR (https://github.com/KnpLabs/KnpMenuBundle/pull/430) added the support of Php 8.
This PR is already 3 month old but never released.

Would it be possible to make a release @garak @stof ? Big thanks

**Comment by Punk-UnDeaD** [comment]
The PR (#430) want "knplabs/knp-menu": "^3.2"
3.1.2 - right version
